<a href="https://colab.research.google.com/github/anujsaxena/AIML/blob/main/AIML_LAb_1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Python Collections**

Tuple

Tuple can store multiple items in a single variable. It is immutable and supports duplicates also

In [ ]:
t=("delhi","noida","dehradun","mumbai")
print(t)
print(type(t))
print(len(t))
print(t[0])
print(t[-1])

('delhi', 'noida', 'dehradun', 'mumbai')
<class 'tuple'>
4
delhi
mumbai


# **A tuple can store numbers, strings, boolean or a mix of all**

In [ ]:
t=(True, False, False, True)
print(t)
print(type(t))
print(len(t))

(True, False, False, True)
<class 'tuple'>
4


In [ ]:
t=(True,1,2,3,4,"Delhi","Mumbai",6,7,False)
print(t)
print(type(t))
print(len(t))

(True, 1, 2, 3, 4, 'Delhi', 'Mumbai', 6, 7, False)
<class 'tuple'>
10


In [ ]:
t = range(0,100,2)
print(type(t))

<class 'range'>


In [ ]:
t = tuple(t)
print(type(t))

<class 'tuple'>


# **Slicing**

In [ ]:
print(t)


(0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98)


In [ ]:
s = t[0:-1]
print(len(t))
print(len(s))
print(s)

50
49
(0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96)


In [ ]:
s1 = s[2:5]
print(s1)

(4, 6, 8)


In [ ]:
s1 = s[:5] #all the elements till 5
print(s1)

(0, 2, 4, 6, 8)


In [ ]:
s1 = s[40:] #all the elements from 40
print(s1)

(80, 82, 84, 86, 88, 90, 92, 94, 96)


# **Delete**

In [ ]:
del s1
print(s1)

NameError: ignored

In [ ]:
t1=t #make a copy of t
t1=[]
print(t1)

[]


In [ ]:
print(t)

(0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98)


In [ ]:
print(t[3])

6


In [ ]:
t[3]=[]
print(t)

TypeError: ignored

In [ ]:
del t[3]
print(t)

TypeError: ignored

In [ ]:
del t
print(t)  #t is removed

NameError: ignored

# **LIST**

Python list is one of the most widely used data types in Python. A Python List can be easily identified by square brackets [ ]. Lists are used to store the data items where each data item is separated by a comma (,). A Python List can have data items of any data type, be it an integer type or a boolean type.

One of the leading reasons why lists are being widely used is that Lists are mutable. Being mutable means, any data item of a List can be replaced by any other data item. This makes Lists different from Tuples, which are also used for storing data items but are immutable.

In [ ]:
t = range(0,100,5)
t = list(t)
print(t)
print(type(t))


[0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]
<class 'list'>


# **Indexing in a List are of two types:**
Positive Indexing – Here the indexing starts from 0, moving from left to right.

Negative Indexing – In this, the indexing starts from right to left and the rightmost element has an index value of -1.

In [ ]:
print("Last element: {}".format(t[-1]))
print(-(len(t)+1))
for i in range(-1,-(len(t)+1),1):
  print(t[i], end=",")

Last element: 95
-21


In [ ]:
print("Last element: {}".format(t[-1]))
for i in range(-1,-(len(t)),-1):
  print(t[i], end=",")

Last element: 95
95,90,85,80,75,70,65,60,55,50,45,40,35,30,25,20,15,10,5,

In [ ]:
print("Last element: {}".format(t[-1]))
for i in range(-1,-(len(t)+1),-1):
  print(t[i], end=",")

Last element: 95
95,90,85,80,75,70,65,60,55,50,45,40,35,30,25,20,15,10,5,0,

In [ ]:
print(t[-20]) #first element

0


# **Deleting**

In [ ]:
t1=t
del t1
print(t1)

NameError: ignored

In [ ]:
t1=t
t1=[]
print(t1)

[]


In [ ]:
t1=t
print(t1)
print(t1[3])
t1[3]=[]
print(t1)


[0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]
15
[0, 5, 10, [], 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]


# **Remove all the occurances of an element from a list**

In [ ]:
l=[1,2,3,2,4,5,7,6,8,1,4,5,7,6,8,9,2]
print(l)
n=int(input("Enter a number to be removed from the list "))

while n in l:
  l.remove(n)
print(l)

[1, 2, 3, 2, 4, 5, 7, 6, 8, 1, 4, 5, 7, 6, 8, 9, 2]
Enter a number to be removed from the list 2
[1, 3, 4, 5, 7, 6, 8, 1, 4, 5, 7, 6, 8, 9]


In [ ]:
l=[1,2,3,2,4,5,7,6,8,1,4,5,7,6,8,9,2]
print(l)
ls = set(l)
print(ls)
l=list(ls)
print(l)

[1, 2, 3, 2, 4, 5, 7, 6, 8, 1, 4, 5, 7, 6, 8, 9, 2]
{1, 2, 3, 4, 5, 6, 7, 8, 9}
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
#delete using index
l=[1,2,3,2,4,5,7,6,8,1,4,5,7,6,8,9,2]
print(l)
l1=l[1]
del l[1]
print("Delete element at index 1 : {0},\n{1}".format(l1,l))
del l[-1]
print("Delete element at index -1 : {}".format(l))

[1, 2, 3, 2, 4, 5, 7, 6, 8, 1, 4, 5, 7, 6, 8, 9, 2]
Delete element at index 1 : 2,
[1, 3, 2, 4, 5, 7, 6, 8, 1, 4, 5, 7, 6, 8, 9, 2]
Delete element at index -1 : [1, 3, 2, 4, 5, 7, 6, 8, 1, 4, 5, 7, 6, 8, 9]


# **Pop out the element**

In [ ]:
print(l)
l.pop(0)
print(l)
l.pop(-1)
print(l)

[1, 3, 2, 4, 5, 7, 6, 8, 1, 4, 5, 7, 6, 8, 9]
[3, 2, 4, 5, 7, 6, 8, 1, 4, 5, 7, 6, 8, 9]
[3, 2, 4, 5, 7, 6, 8, 1, 4, 5, 7, 6, 8]


# **Removing a slice**
Elemements can be removed in a range by either giving a start and stop range with : in between (example - l(2:4)). All the elemnts from a starting point can be removved by omitting the stop range (example: l(2:)). The indexing can be from reverse order also like: l(-2:)

In [ ]:
l=[1,2,3,2,4,5,7,6,8,1,4,5,7,6,8,9,2]
print(l)
ls=l[0:3]
print(ls)
del l[0:3]
print("Delete from 0 to 3 :{}".format(l))
del l[6:]
print("Delete from 6 till end :{}".format(l))
del l[-3:]
print("Delete from -3 till beginning :{}".format(l))

[1, 2, 3, 2, 4, 5, 7, 6, 8, 1, 4, 5, 7, 6, 8, 9, 2]
[1, 2, 3]
Delete from 0 to 3 :[2, 4, 5, 7, 6, 8, 1, 4, 5, 7, 6, 8, 9, 2]
Delete from 6 till end :[2, 4, 5, 7, 6, 8]
Delete from -3 till beginning :[2, 4, 5]


# **Remove all the elements**

In [ ]:
l=[1,2,3,2,4,5,7,6,8,1,4,5,7,6,8,9,2]
print(l)
l.clear()
print(l)

[1, 2, 3, 2, 4, 5, 7, 6, 8, 1, 4, 5, 7, 6, 8, 9, 2]
[]


# **Append**

In [ ]:
a = [0, 1, 1, 2, 3, 5, 8, 13]
b = [5., "girl", 2+0j, "horse", 21]
c =a+b
print(c)

[0, 1, 1, 2, 3, 5, 8, 13, 5.0, 'girl', (2+0j), 'horse', 21]


In [ ]:
c[0]=c[0]+4
print(c)

[4, 1, 1, 2, 3, 5, 8, 13, 5.0, 'girl', (2+0j), 'horse', 21]


# **Exchange the element**

In [ ]:
l=[1,3,4,5,6,7,8,9,10,11,12]
print(l)

[1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]


In [ ]:
l[0],l[-1]=l[-1],l[0]
print(l)

[12, 3, 4, 5, 6, 7, 8, 9, 10, 11, 1]


# **Multidimensional list**

In [ ]:
l=[[1,2,3,4],["a","b","c"],[True, False, True]]
print(l)

[[1, 2, 3, 4], ['a', 'b', 'c'], [True, False, True]]


In [ ]:
l.append(["hello","how are","you"])
print(l)

[[1, 2, 3, 4], ['a', 'b', 'c'], [True, False, True], ['hello', 'how are', 'you']]


In [ ]:
print(l[0][0])
print(l[1][0])
print(l[2][0])
print(l[3][0])

1
a
True
hello


# **Extend**

In [ ]:
l[0].extend([7,9,10,11])
print(l)

[[1, 2, 3, 4, 7, 9, 10, 11], ['a', 'b', 'c'], [True, False, True], ['hello', 'how are', 'you']]


In [ ]:
l[0].extend(["piyush","nikki"])
print(l)

[[1, 2, 3, 4, 7, 9, 10, 11, 'piyush', 'nikki'], ['a', 'b', 'c'], [True, False, True], ['hello', 'how are', 'you']]


In [ ]:
print(l[0][9])

nikki


In [ ]:
print(len(l[0]))

10


In [ ]:
for i in range(len(l)):        #loop for the row
  for j in range(len(l[i])):    #for the column
    print(l[i][j],end=" ")
  print()

1 2 3 4 7 9 10 11 piyush nikki 
a b c 
True False True 
hello how are you 


In [ ]:
for i in range(len(l)):        #loop for the row
  for j in range(len(l[i])):    #for the column
    print(l[i][j],end=" ")
  

1 2 3 4 7 9 10 11 piyush nikki a b c True False True hello how are you 

In [ ]:
print(len(l))

4


In [ ]:
print(range(len(l)))

range(0, 4)


In [ ]:
print(len(l[0]))
print(len(l[1]))
print(len(l[2]))
print(len(l[3]))

10
3
3
3


# **Arrays**
From the prvious knolwedge of arrays we know that "Arrays are a linear collection of similar data types". In python Array are like lists only which hold a group of items. Array stores items within square brackets and can store non-unique values. To create an array we need a module. One can use Numpy or array module for the same.

To create an array using array module one has to give the value type. The syntax is :

ar = array.array(<'value type'>, <[data]>)

In [ ]:
import array
ar = array.array('i',[1,2,3,4,5])
print(ar)
for i in ar:
  print(i)

array('i', [1, 2, 3, 4, 5])
1
2
3
4
5


In [ ]:
import array
ar = array.array('u',['a','b','c'])
print(ar)
for j in ar:
  print(j)

array('u', 'abc')
a
b
c


In [ ]:
import array
ar = array.array('d',[2,4,5,6,7])
print(ar)
for i in ar:
  print(i)

array('d', [2.0, 4.0, 5.0, 6.0, 7.0])
2.0
4.0
5.0
6.0
7.0


In [ ]:
import array
ar = array.array('b',[0,1,0,0,1])
print(ar)
for i in ar:
  print(i)

array('b', [0, 1, 0, 0, 1])
0
1
0
0
1


In [ ]:
import array
ar = array.array('b',[True,False,True,True,False])
print(ar)
for i in ar:
  print(i)

array('b', [1, 0, 1, 1, 0])
1
0
1
1
0


In [ ]:
l=[1,2,3,4,5,6,7,8,9,10]
ar = array.array('i',l)
print(ar)
for i in ar:
  print(i)

array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
1
2
3
4
5
6
7
8
9
10


# **Creating array using Numpy**

In [ ]:
import numpy as np
ar = np.array([2,3,5,1,6,8,7,9])
print(ar)
print(type(ar))

[2 3 5 1 6 8 7 9]
<class 'numpy.ndarray'>


# **Converting a list into an array**

In [ ]:
l =[3,1,8,9,10]
print(l)
print(type(l))
ar= np.array(l)
print(ar)
print(type(ar))

[3, 1, 8, 9, 10]
<class 'list'>
[ 3  1  8  9 10]
<class 'numpy.ndarray'>


# **linspace**
The linspace function creates an array of evenly spaced points between a starting point and an ending point.

The form of the function is linspace(start, stop, N). If the third argument N is omitted, then N=50.

In [ ]:
l =np.linspace(1,10)
print(l)
print(type(l))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
<class 'numpy.ndarray'>


In [ ]:
l =np.linspace(1,10,10)
print(l)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
ar = array.array('d',l)
print(ar)

array('d', [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0])


In [ ]:
print(type(ar))

<class 'array.array'>


# **logspace**
NumPy also has a closely related function logspace that produces evenly spaced points on a logarithmically spaced scale. The arguments are the same as those for linspace except that start and stop refer to a power of 10. That is, the array starts at `10^start and 10^stop` .

In [ ]:
lg = np.logspace(1,3,10)
print(lg)

[  10.           16.68100537   27.82559402   46.41588834   77.42636827
  129.1549665   215.443469    359.38136638  599.48425032 1000.        ]


In [ ]:
print(type(lg))

<class 'numpy.ndarray'>


In [ ]:
ar = array.array('d',lg)
print(ar)

array('d', [10.0, 16.68100537200059, 27.825594022071243, 46.41588833612777, 77.4263682681127, 129.1549665014884, 215.44346900318823, 359.38136638046257, 599.4842503189409, 1000.0])


In [ ]:
for i in ar:
  print(i)

10.0
16.68100537200059
27.825594022071243
46.41588833612777
77.4263682681127
129.1549665014884
215.44346900318823
359.38136638046257
599.4842503189409
1000.0


In [ ]:
print(ar[2:5])

array('d', [27.825594022071243, 46.41588833612777, 77.4263682681127])


In [ ]:
arr= ar[2:5]
for i in arr:
  print(i)

27.825594022071243
46.41588833612777
77.4263682681127


# **arange**
The third way arrays can be created is using the NumPy arange function, which is similar to the Python range function for creating lists. The form of the function is arange(start, stop, step). If the third argument is omitted step=1. If the first and third arguments are omitted, then start=0and step=1.

In [ ]:
n=np.arange(1,10,2)
print(n)

[1 3 5 7 9]


In [ ]:
print(type(n))

<class 'numpy.ndarray'>


In [ ]:
arr=array.array('i',n)
print(arr)
print(type(arr))

array('i', [1, 3, 5, 7, 9])
<class 'array.array'>


In [ ]:
z=np.zeros(6)
print(z)

[0. 0. 0. 0. 0. 0.]


In [ ]:
o=np.ones(9)
print(o,end=",")
print(type(o))

[1. 1. 1. 1. 1. 1. 1. 1. 1.],<class 'numpy.ndarray'>


# **Multidimensioanl arrays**
We can use vertical stack to create an n-dimensional array

In [ ]:
a = np.array([1,2,3])
print(a)
print()
b = np.array([4,5,6])
print(b)


[1 2 3]

[4 5 6]


In [ ]:
c = np.vstack((a, b))
print(c)

[[1 2 3]
 [4 5 6]]


In [ ]:
#check the dimension
print(c.shape)

(2, 3)


# **Concatinating array**
We can use horizontal stack to concatenate the arrays

In [ ]:
c = np.hstack((a, b))
print(c)

[1 2 3 4 5 6]


In [ ]:
print(c.shape)

(6,)


# **Difference between List and array**

Numpy arrays are typed arrays that hold homogeneous, densely packed numbers in memory.
The list in memory of a Python list is heterogeneous; it holds pointers to objects rather than the numbers themselves.
This implies that every time the function has to access a number, Python list requires dereferencing a reference. While numpy arrays may be directly processed by numpy vector operations, these vector operations are far quicker than anything you can do with a list.



The disadvantage of using a numpy array is that if you need to access individual items in the array, you'll have to box/unbox the number into a python numeric object, which can be slow in some cases; and it can't handle heterogeneous data.

For an array we need a seperate module but List is inbuilt, it does not require a seperate module.

Array can store data more efficiently than List

Arrays are good for mathematical opeartions. A List cannot direclty handle a mathematical operation. Let us see with an example:

In [ ]:
l=[3,6,8,9,10]
ar = np.array([2,7,8,9,10])
opr = ar/2
print(opr)
opl=l/2
print(op1)

[1.  3.5 4.  4.5 5. ]


TypeError: ignored

# **Multiple Lines**

In [ ]:
s ='''Welcome to the world pf computing
let us learn python.
join us today'''
print(s)
print(type(s))

Welcome to the world pf computing
let us learn python.
join us today
<class 'str'>


In [ ]:
if 'join' in s:
  print('join us')
else:
  print('no issues')

join us


In [ ]:
print(len(s))

68


In [ ]:
#one lement at a time
for n in s:
  print(n)

W
e
l
c
o
m
e
 
t
o
 
t
h
e
 
w
o
r
l
d
 
p
f
 
c
o
m
p
u
t
i
n
g


l
e
t
 
u
s
 
l
e
a
r
n
 
p
y
t
h
o
n
.


j
o
i
n
 
u
s
 
t
o
d
a
y


In [ ]:
#tokens using split function
for n in s.split():
  print(n, end=" ")


Welcome to the world pf computing let us learn python. join us today 